batch_size: 128
checkpoint_callback: null
checkpoint_root: ./data/checkpoint/deep_geo/svhn/final/reproduce/class_5/run_1
early_stopping_callback: null
epochs: 3
random_seed: 296
results_root: ./data/results/deep_geo/svhn/final/reproduce/class_5/run_1
test_batch_size: 1024
test_checkpoint_path: ./data/checkpoint/deep_geo/svhn/final/reproduce/class_5/run_1/checkpoint.h5
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 8
      - 9
    dataset_type: svhn
    transform_kwargs: {}
  normal:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 5
    dataset_type: svhn
    transform_kwargs: {}
train_dataset:
  dataset_kwargs:
    root: ./data/data/svhn
    split: train
    target_classes:
    - 5
  dataset_type: svhn
  transform_kwargs: {}
val_dataset: null
