adam_kwargs:
  lr: 0.0002
batch_sizes:
  64: 128
checkpoint_root: ./data/checkpoint/dpa/camelyon16/final/wo_pg_L1_unsupervised/class_healthy/run_0
dec:
  kwargs:
    inner_dims:
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
  type: residual18
early_stoping_patience: 1000000
early_stopping_min_delta: 0.001
early_stopping_patience: 3
enc:
  kwargs:
    inner_dims:
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
  type: residual18
finetune_from: null
image_dim: 3
image_rec_loss:
  loss_kwargs: {}
  loss_type: l1
image_sample_iter: 1000
initial_image_res: 64
iters_per_res:
  64:
    stab: 46000
latent_dim: 32
latent_res: 16
log_iter: 10
log_root: ./data/logs/dpa/camelyon16/final/wo_pg_L1_unsupervised/class_healthy/run_0
max_image_res: 64
random_seed: 6012
results_root: ./data/results/dpa/camelyon16/final/wo_pg_L1_unsupervised/class_healthy/run_0
stab_iter: 100000
test_batch_size: 32
test_datasets:
  anomaly:
    dataset_kwargs:
      image_root: ./data/data/camelyon16/x10
      split: test
      split_root: ./folds/train_test_split/camelyon16/healthy/anomaly/
    dataset_type: camelyon16
    transform_kwargs:
      crop_size: 64
  normal:
    dataset_kwargs:
      image_root: ./data/data/camelyon16/x10
      split: test
      split_root: ./folds/train_test_split/camelyon16/healthy/normal/
    dataset_type: camelyon16
    transform_kwargs:
      crop_size: 64
test_model_path: ./data/checkpoint/dpa/camelyon16/final/wo_pg_L1_unsupervised/class_healthy/run_0/anomaly_detection.tar
train_dataset:
  dataset_kwargs:
    image_root: ./data/data/camelyon16/x10
    split: train
    split_root: ./folds/train_test_split/camelyon16/healthy/normal/
  dataset_type: camelyon16
  transform_kwargs:
    crop_size: 64
    random_crop: true
    random_flip: true
trns_iter: 0
val_dataset:
  dataset_kwargs:
    image_root: ./data/data/camelyon16/x10
    split: train
    split_root: ./folds/train_test_split/camelyon16/healthy/normal/
  dataset_type: camelyon16
  transform_kwargs:
    crop_size: 64
val_iter: 1000000
verbose: true
