batch_size: 128
checkpoint_callback: null
checkpoint_root: ./data/checkpoint/deep_geo/cifar10/final/with_cv//class_2/run_2
early_stopping_callback: null
epochs: 3
random_seed: 4154
results_root: ./data/results/deep_geo/cifar10/final/with_cv/class_2/run_2
test_batch_size: 1024
test_checkpoint_path: ./data/checkpoint/deep_geo/cifar10/final/with_cv//class_2/run_2/checkpoint.h5
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/cifar10
      split: test
      target_classes:
      - 0
      - 1
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      target_indexes_path: null
    dataset_type: cifar10
    transform_kwargs: {}
  normal:
    dataset_kwargs:
      root: ./data/data/cifar10
      split: test
      target_classes:
      - 2
      target_indexes_path: null
    dataset_type: cifar10
    transform_kwargs: {}
train_dataset:
  dataset_kwargs:
    root: ./data/data/cifar10
    split: train
    target_classes:
    - 2
    target_indexes_path: null
  dataset_type: cifar10
  transform_kwargs: {}
val_dataset:
  dataset_kwargs:
    root: ./data/data/cifar10
    split: train
    target_classes:
    - 2
    target_indexes_path: null
  dataset_type: cifar10
  transform_kwargs: {}
