batch_size: 32
feature_extraction_type: concat
random_seed: 6957
results_root: ./data/results/deep_if/svhn/final/with_cv/class_2/run_1
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 0
      - 1
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      target_indexes_path: null
    dataset_type: svhn
    transform_kwargs:
      to_grayscale: false
  normal:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 2
      target_indexes_path: null
    dataset_type: svhn
    transform_kwargs:
      to_grayscale: false
train_dataset:
  dataset_kwargs:
    root: ./data/data/svhn
    split: train
    target_classes:
    - 2
    target_indexes_path: null
  dataset_type: svhn
  transform_kwargs:
    to_grayscale: false
