#random_seed: 1234
#results_root: ./data/results/deep_if/cifar/repeat_exp/0

batch_size: 32
feature_extraction_type: concat

train_dataset:
  dataset_type: svhn
  dataset_kwargs:
    root: ./data/data/svhn
#    target_classes: [0]
    split: train
  transform_kwargs: {}

test_datasets:
  normal:
    dataset_type: svhn
    dataset_kwargs:
      root: ./data/data/svhn
#      target_classes: [0]
      split: test
    transform_kwargs: {}
  anomaly:
    dataset_type: svhn
    dataset_kwargs:
      root: ./data/data/svhn
#      target_classes: [1, 2, 3, 4, 5, 6, 7, 8, 9]
      split: test
    transform_kwargs: {}

