batch_size: 32
feature_extraction_type: mixed_7a
random_seed: 9167
results_root: ./data/results/deep_if/svhn/final/with_cv/class_4/run_2
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 0
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 9
      target_indexes_path: null
    dataset_type: svhn
    transform_kwargs:
      to_grayscale: false
  normal:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 4
      target_indexes_path: null
    dataset_type: svhn
    transform_kwargs:
      to_grayscale: false
train_dataset:
  dataset_kwargs:
    root: ./data/data/svhn
    split: train
    target_classes:
    - 4
    target_indexes_path: null
  dataset_type: svhn
  transform_kwargs:
    to_grayscale: false
