adam_kwargs:
  lr: 0.01
batch_sizes:
  32: 128
checkpoint_root: ./data/checkpoint/dpa/cifar10/final/wo_pg/class_1/run_0
dec:
  kwargs:
    inner_dims:
    - 8
    - 8
    - 8
    - 8
  type: residual18
early_stoping_patience: 1000000
early_stopping_min_delta: 0.001
early_stopping_patience: 3
enc:
  kwargs:
    inner_dims:
    - 8
    - 8
    - 8
    - 8
  type: residual18
finetune_from: null
image_dim: 3
image_rec_loss:
  loss_kwargs:
    use_smooth_pg: false
    weights_per_resolution:
      32:
        feature_weights:
          r42: 1
        img_weight: 0
  loss_type: relative_perceptual_L1
image_sample_iter: 1000
initial_image_res: 32
iters_per_res:
  32:
    stab: 7333
latent_dim: 8
latent_res: 1
log_iter: 10
log_root: ./data/logs/dpa/cifar10/final/wo_pg/class_1/run_0
max_image_res: 32
random_seed: 2255
results_root: ./data/results/dpa/cifar10/final/wo_pg/class_1/run_0
stab_iter: 20000
test_batch_size: 32
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/cifar10
      split: test
      target_classes:
      - 0
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      target_indexes_path: null
    dataset_type: cifar10
    transform_kwargs: {}
  normal:
    dataset_kwargs:
      root: ./data/data/cifar10
      split: test
      target_classes:
      - 1
      target_indexes_path: null
    dataset_type: cifar10
    transform_kwargs: {}
test_model_path: ./data/checkpoint/dpa/cifar10/final/wo_pg/class_1/run_0/anomaly_detection.tar
train_dataset:
  dataset_kwargs:
    root: ./data/data/cifar10
    split: train
    target_classes:
    - 1
    target_indexes_path: null
  dataset_type: cifar10
  transform_kwargs: {}
trns_iter: 0
val_dataset:
  dataset_kwargs:
    root: ./data/data/cifar10
    split: train
    target_classes:
    - 1
    target_indexes_path: null
  dataset_type: cifar10
  transform_kwargs: {}
val_iter: 1000000
verbose: true
