batch_size: 32
feature_extraction_type: mixed_7a
random_seed: 8119
results_root: ./data/results/deep_if/nih/final/with_cv/class_subset/run_2
test_datasets:
  anomaly:
    dataset_kwargs:
      image_root: ./data/data/nih_300/
      split: test
      split_root: ./folds/train_test_split/nih/subset/anomaly/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: false
      resize: 64
  normal:
    dataset_kwargs:
      image_root: ./data/data/nih_300/
      split: test
      split_root: ./folds/train_test_split/nih/subset/normal/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: false
      resize: 64
train_dataset:
  dataset_kwargs:
    image_root: ./data/data/nih_300/
    split: train
    split_root: ./folds/train_test_split/nih/subset/normal/
  dataset_type: nih
  transform_kwargs:
    crop_size: 224
    equalize_hist: false
    resize: 64
