batch_size: 32
feature_extraction_type: concat
random_seed: 9830
results_root: ./data/results/deep_if/svhn/final/reproduce/class_5/run_2
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 6
      - 7
      - 8
      - 9
    dataset_type: svhn
    transform_kwargs: {}
  normal:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 5
    dataset_type: svhn
    transform_kwargs: {}
train_dataset:
  dataset_kwargs:
    root: ./data/data/svhn
    split: train
    target_classes:
    - 5
  dataset_type: svhn
  transform_kwargs: {}
