batch_size: 32
feature_extraction_type: concat
random_seed: 3626
results_root: ./data/results/deep_if/svhn/final/reproduce/class_8/run_1
test_datasets:
  anomaly:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
    dataset_type: svhn
    transform_kwargs: {}
  normal:
    dataset_kwargs:
      root: ./data/data/svhn
      split: test
      target_classes:
      - 8
    dataset_type: svhn
    transform_kwargs: {}
train_dataset:
  dataset_kwargs:
    root: ./data/data/svhn
    split: train
    target_classes:
    - 8
  dataset_type: svhn
  transform_kwargs: {}
