adam_kwargs:
  ddis:
    betas:
    - 0.5
    - 0.99
    lr: 0.0005
  edis:
    betas:
    - 0.5
    - 0.99
    lr: 0.0005
  enc_dec:
    betas:
    - 0.5
    - 0.99
    lr: 0.0002
batch_size: 32
checkpoint_root: ./data/checkpoint_tmp/piad/nih/final/with_cv/class_AP/run_2
ddis:
  kwargs:
    inner_dims:
    - 32
    - 64
    - 128
    - 128
    - 128
  type: residual9
dec:
  kwargs:
    inner_dims:
    - 256
    - 256
    - 128
    - 64
    - 32
  type: residual9
edis:
  kwargs:
    inner_dims:
    - 1024
    - 1024
enc:
  kwargs:
    inner_dims:
    - 32
    - 64
    - 128
    - 256
    - 256
  type: residual9
finetune_from: null
image_adv_loss:
  loss_kwargs:
    gradient_penalty: 10
    lambd: 1
    norm_penalty: 0.001
  loss_type: wasserstein
image_dim: 1
image_rec_loss:
  loss_kwargs:
    feature_weights:
      r32: 1
      r42: 1
    img_weight: 0
  loss_type: relative_perceptual_L1
image_res: 64
image_sample_iter: 5000
initial_image_res: 64
iters: 40000
latent_adv_loss:
  loss_kwargs:
    gradient_penalty: 10
    lambd: 1
    norm_penalty: 0.001
  loss_type: wasserstein
latent_dim: 256
latent_res: 1
log_iter: 10
log_root: ./data/logs_tmp/piad/nih/final/with_cv/class_AP/run_2
n_dis: 2
random_seed: 1927
results_root: ./data/results/piad/nih/final/with_cv/class_AP/run_2
test_batch_size: 32
test_datasets:
  anomaly:
    dataset_kwargs:
      image_root: ./data/data/nih_300/
      split: test
      split_root: ./folds/train_test_split/nih/AP/anomaly/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: true
      resize: 64
  normal:
    dataset_kwargs:
      image_root: ./data/data/nih_300/
      split: test
      split_root: ./folds/train_test_split/nih/AP/normal/
    dataset_type: nih
    transform_kwargs:
      crop_size: 224
      equalize_hist: true
      resize: 64
test_model_path: ./data/checkpoint_tmp/piad/nih/final/with_cv/class_AP/run_2/anomaly_detection.tar
train_dataset:
  dataset_kwargs:
    image_root: ./data/data/nih_300/
    split: train
    split_root: ./folds/train_test_split/nih/AP/normal/
  dataset_type: nih
  transform_kwargs:
    crop_size: 224
    equalize_hist: false
    resize: 64
update_grad_norm_iter: 100
val_dataset:
  dataset_kwargs:
    image_root: ./data/data/nih_300/
    split: train
    split_root: ./folds/train_test_split/nih/AP/normal/
  dataset_type: nih
  transform_kwargs:
    crop_size: 224
    equalize_hist: false
    resize: 64
val_iter: 1000000
verbose: true
